$ErrorActionPreference = "Stop"

Write-Host "PrismMind production deployment example"
Write-Host "This script prints commands only. Review DEPLOYMENT.md before running them."
Write-Host ""
Write-Host "1. Prepare backend/.env.production from backend/.env.production.example on the server."
Write-Host "2. Validate Compose:"
Write-Host "   powershell -ExecutionPolicy Bypass -File scripts/check_prod_compose.ps1"
Write-Host "3. Build and start:"
Write-Host "   docker compose -f docker-compose.prod.yml --env-file backend/.env.production up -d --build"
Write-Host "4. Run migrations:"
Write-Host "   docker compose -f docker-compose.prod.yml --env-file backend/.env.production exec backend alembic upgrade head"
Write-Host "5. Seed admin when needed:"
Write-Host "   docker compose -f docker-compose.prod.yml --env-file backend/.env.production exec backend python scripts/seed_admin.py"
Write-Host ""
Write-Host "Never run docker compose down -v in production unless you intentionally want to delete persistent data."
